from __future__ import annotations

from abc import ABC, abstractmethod

from app.models.signal import LLMClassificationResult


class LLMClassifier(ABC):
    @abstractmethod
    def classify_text(self, ticker: str, text: str, item_id: str | None = None) -> LLMClassificationResult:
        raise NotImplementedError

    @abstractmethod
    def summarize_stock_discussion(self, ticker: str, texts: list[str]) -> str:
        raise NotImplementedError


class MockLLMClassifier(LLMClassifier):
    def classify_text(self, ticker: str, text: str, item_id: str | None = None) -> LLMClassificationResult:
        lowered = text.lower()
        discussion_type = "thesis-driven" if "because" in lowered or "why" in lowered else "headline-chatter"
        return LLMClassificationResult(
            classification_id=f"{ticker}:{item_id or 'aggregate'}",
            ticker=ticker,
            item_id=item_id,
            discussion_type=discussion_type,
            confidence=0.35,
            summary=f"Placeholder classification for {ticker}.",
        )

    def summarize_stock_discussion(self, ticker: str, texts: list[str]) -> str:
        return f"{ticker} discussion summary generated by mock classifier from {len(texts)} items."
