from __future__ import annotations

import os
from abc import ABC, abstractmethod

from pydantic import BaseModel, Field

from app.config import LLMConfig
from app.models.signal import LLMClassificationResult


class LLMClassifier(ABC):
    @abstractmethod
    def classify_text(self, ticker: str, text: str, item_id: str | None = None) -> LLMClassificationResult:
        raise NotImplementedError

    @abstractmethod
    def summarize_stock_discussion(self, ticker: str, texts: list[str]) -> str:
        raise NotImplementedError


class OpenAIClassificationPayload(BaseModel):
    discussion_type: str = Field(
        description="One of thesis-driven, headline-chatter, pump-meme, post-price-move, mixed, or unclear."
    )
    confidence: float = Field(ge=0.0, le=1.0)
    summary: str = Field(description="Short analyst-facing summary of the stock discussion.")


class MockLLMClassifier(LLMClassifier):
    def classify_text(self, ticker: str, text: str, item_id: str | None = None) -> LLMClassificationResult:
        lowered = text.lower()
        discussion_type = "thesis-driven" if "because" in lowered or "why" in lowered else "headline-chatter"
        return LLMClassificationResult(
            classification_id=f"{ticker}:{item_id or 'aggregate'}",
            ticker=ticker,
            item_id=item_id,
            discussion_type=discussion_type,
            confidence=0.35,
            summary=f"Placeholder classification for {ticker}.",
        )

    def summarize_stock_discussion(self, ticker: str, texts: list[str]) -> str:
        return f"{ticker} discussion summary generated by mock classifier from {len(texts)} items."


class OpenAIResponsesLLMClassifier(LLMClassifier):
    def __init__(self, config: LLMConfig) -> None:
        self.config = config
        api_key = os.getenv(config.api_key_env_var)
        if not api_key:
            raise ValueError(
                f"Missing API key in environment variable {config.api_key_env_var} for OpenAI LLM provider."
            )

        try:
            from openai import OpenAI
        except ImportError as exc:
            raise RuntimeError("The openai package is not installed. Install project dependencies first.") from exc

        client_kwargs: dict[str, str] = {"api_key": api_key}
        if config.base_url:
            client_kwargs["base_url"] = config.base_url
        self.client = OpenAI(**client_kwargs)

    def classify_text(self, ticker: str, text: str, item_id: str | None = None) -> LLMClassificationResult:
        truncated_text = text[: self.config.max_input_chars]
        response = self.client.responses.parse(
            model=self.config.model,
            input=[
                {"role": "system", "content": self.config.system_prompt},
                {
                    "role": "user",
                    "content": (
                        f"Ticker: {ticker}\n"
                        "Classify the Reddit discussion for manual equity research.\n"
                        "Use the allowed labels only: thesis-driven, headline-chatter, pump-meme, "
                        "post-price-move, mixed, unclear.\n"
                        "Return a concise summary focused on why the ticker is being discussed.\n\n"
                        f"Discussion text:\n{truncated_text}"
                    ),
                },
            ],
            text_format=OpenAIClassificationPayload,
        )
        parsed = response.output_parsed
        if parsed is None:
            raise RuntimeError(f"OpenAI returned no parsed classification for {ticker}.")

        return LLMClassificationResult(
            classification_id=f"{ticker}:{item_id or 'aggregate'}",
            ticker=ticker,
            item_id=item_id,
            discussion_type=parsed.discussion_type,
            confidence=parsed.confidence,
            summary=parsed.summary,
        )

    def summarize_stock_discussion(self, ticker: str, texts: list[str]) -> str:
        merged = "\n\n".join(texts)[: self.config.max_input_chars]
        response = self.client.responses.create(
            model=self.config.model,
            input=[
                {"role": "system", "content": self.config.system_prompt},
                {
                    "role": "user",
                    "content": (
                        f"Ticker: {ticker}\n"
                        "Summarize the key Reddit discussion points for a human stock analyst in 2-3 sentences.\n\n"
                        f"Discussion text:\n{merged}"
                    ),
                },
            ],
        )
        return response.output_text.strip()


def build_llm_classifier(config: LLMConfig) -> LLMClassifier:
    if not config.enabled or config.provider == "mock":
        return MockLLMClassifier()
    if config.provider == "openai":
        return OpenAIResponsesLLMClassifier(config)
    raise ValueError(f"Unsupported LLM provider: {config.provider}")
